name: default

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 8.0.192, 9.0.x, 10, 11.0.x, 11.0.3, 12, 13 ]

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}

    - name: Cache .m2
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean verify

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: examples/coverage-aggregate/target/site/jacoco-aggregate/jacoco.xml
